# ╭─────────────────────────────────────────────────────────────────────────────────────────╮
# │ ➸ [ BOT ]
# ╰─────────────────────────────────────────────────────────────────────────────────────────╯

STATUS: ""
ACTIVITY_NAME: ""
ACTIVITY_TYPE: ""